# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: add.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("add.proto", :syntax => :proto3) do
    add_message "calc.AddRequest" do
      optional :number, :int32, 1
    end
    add_message "calc.AddResponse" do
      optional :answer, :int32, 1
    end
  end
end

module Calc
  AddRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("calc.AddRequest").msgclass
  AddResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("calc.AddResponse").msgclass
end
