# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: add.proto for package 'calc'

require 'grpc'
require 'add_pb'

module Calc
  module Add
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'calc.Add'

      rpc :Add, ::Calc::AddRequest, ::Calc::AddResponse
    end

    Stub = Service.rpc_stub_class
  end
end
