# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: import.proto for package 'import'

require 'grpc'
require 'import_pb'

module Import
  module Upload
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'import.Upload'

      rpc :Send, stream(::Import::UploadRequest), ::Import::UploadResponse
    end

    Stub = Service.rpc_stub_class
  end
end
