# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple_stream.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("simple_stream.proto", :syntax => :proto3) do
    add_message "EchoMessage" do
      optional :msg, :string, 1
    end
  end
end

EchoMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EchoMessage").msgclass
